package com.hardcoders.csc468.weather;

import com.hardcoders.csc468.weather.XMLImport.XmlWeatherDataPoint;
import com.hardcoders.csc468.weather.model.WeatherDataPoint;
import java.io.File;
import java.io.FilenameFilter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.FILES_AND_DIRECTORIES;
import javax.swing.JTextArea;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.hardcoders.csc468.weather.graph.Graph;
import com.hardcoders.csc468.weather.graph.InteractiveLineGraph;
import java.util.Date;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author Mack Smith
 */
public class WeathermanWindow extends javax.swing.JFrame {

    private List<XmlWeatherDataPoint> dataPoints;
    private boolean graphUpdated;
    
    /**
     * Creates new form WeathermanWindow
     */
    public WeathermanWindow() {
        initComponents();

        dataPoints = new ArrayList<XmlWeatherDataPoint>();

        
        graphUpdated = false;
                
        startDate.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (graphUpdated) return;
                graphUpdated = true;
                
                lineGraph.setDomainLowerBound((double) ((Date) startDate.getValue()).getTime());
                lineGraph.redraw();
                lineGraph.repaint();
                
                graphUpdated = false;
            }
        });
        endDate.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if (graphUpdated) return;
                graphUpdated = true;
                
                lineGraph.setDomainUpperBound((double) ((Date) endDate.getValue()).getTime());
                lineGraph.redraw();
                lineGraph.repaint();
                
                graphUpdated = false;
            }
        });
        lineGraph.addGraphListener(new InteractiveLineGraph.GraphListener() {
            @Override
            public void onGraphChanged(Graph graph) {
                if (graph != lineGraph) return;
                if (graphUpdated) return;
                graphUpdated = true;
                
                if (lineGraph.getDomainLowerBound() != null) {
                    startDate.setValue(new Date((long) lineGraph.getDomainLowerBound().doubleValue()));
                }
                if (lineGraph.getDomainUpperBound() != null) {
                    endDate.setValue(new Date((long) lineGraph.getDomainUpperBound().doubleValue()));
                }
                
                graphUpdated = false;
            }
        });
        
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(100), 10.0).getTemperatureAsDataPoint());
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(250), 10.0).getTemperatureAsDataPoint());
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(275), 12.0).getTemperatureAsDataPoint());
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(325), 8.0).getTemperatureAsDataPoint());
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(350), 10.0).getTemperatureAsDataPoint());
        lineGraph.addDataPoint(new SimpleWeatherDataPoint(new Date(500), 10.0).getTemperatureAsDataPoint());
        
        lineGraph.setDomainLowerBound(50.0);
        lineGraph.setDomainUpperBound(550.0);
        lineGraph.setRangeUpperBound(15.0);
        lineGraph.setRangeLowerBound(5.0);
        
        lineGraph.redraw();
    }
    
    /**
     *  Creates new form WeathermanWindow with a title
    */
    public WeathermanWindow(String title) {
        this();
        this.setTitle(title);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataOptions = new javax.swing.ButtonGroup();
        temperatureButton = new javax.swing.JRadioButton();
        windSpeedButton = new javax.swing.JRadioButton();
        rainfallButton = new javax.swing.JRadioButton();
        humidityButton = new javax.swing.JRadioButton();
        pressureButton = new javax.swing.JRadioButton();
        windGustButton = new javax.swing.JRadioButton();
        windChillButton = new javax.swing.JRadioButton();
        uvButton = new javax.swing.JRadioButton();
        heatButton = new javax.swing.JRadioButton();
        tempLabel = new javax.swing.JLabel();
        tempVal = new javax.swing.JLabel();
        lineGraph = new com.hardcoders.csc468.weather.WeathermanLineGraph();
        endDate = new javax.swing.JSpinner();
        startDate = new javax.swing.JSpinner();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        menuQuit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataOptions.add(temperatureButton);
        temperatureButton.setText("Temperature");
        temperatureButton.setToolTipText("Switches graph data to temperature");
        temperatureButton.setBorder(null);
        temperatureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/temp.png"))); // NOI18N
        temperatureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureButtonActionPerformed(evt);
            }
        });

        dataOptions.add(windSpeedButton);
        windSpeedButton.setText("Wind Speed");
        windSpeedButton.setToolTipText("Switches graph data to wind speed");
        windSpeedButton.setBorder(null);
        windSpeedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/windspeed.png"))); // NOI18N
        windSpeedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windSpeedButtonActionPerformed(evt);
            }
        });

        dataOptions.add(rainfallButton);
        rainfallButton.setText("Rainfall");
        rainfallButton.setToolTipText("Switches graph data to rainfall");
        rainfallButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/rainfall.png"))); // NOI18N

        dataOptions.add(humidityButton);
        humidityButton.setText("Humidity");
        humidityButton.setToolTipText("Switches graph data to humidity");
        humidityButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/humidity.png"))); // NOI18N

        dataOptions.add(pressureButton);
        pressureButton.setText("Pressure");
        pressureButton.setToolTipText("Switches graph data to pressure");
        pressureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/pressure.png"))); // NOI18N
        pressureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressureButtonActionPerformed(evt);
            }
        });

        dataOptions.add(windGustButton);
        windGustButton.setText("Wind Gust");
        windGustButton.setToolTipText("Switches graph data to wind gust");
        windGustButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/windgust.png"))); // NOI18N

        dataOptions.add(windChillButton);
        windChillButton.setText("Wind Chill");
        windChillButton.setToolTipText("Switches graph data to wind chill");
        windChillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/windchill.png"))); // NOI18N
        windChillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windChillButtonActionPerformed(evt);
            }
        });

        dataOptions.add(uvButton);
        uvButton.setText("UV Index");
        uvButton.setToolTipText("Switches graph data to UV index");
        uvButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/uvindex.png"))); // NOI18N
        uvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvButtonActionPerformed(evt);
            }
        });

        dataOptions.add(heatButton);
        heatButton.setText("Heat Index");
        heatButton.setToolTipText("Switches graph data to heat index");
        heatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hardcoders/csc468/weather/icons/heatindex.png"))); // NOI18N

        tempLabel.setText("Temperature");

        tempVal.setText(lineGraph.getSelectedDataPoint().getTemperature().toString());

        endDate.setModel(new javax.swing.SpinnerDateModel());
        endDate.setToolTipText("End date");
        endDate.setValue(new Date());

        startDate.setModel(new javax.swing.SpinnerDateModel());
        startDate.setToolTipText("Start date");
        startDate.setValue(new Date());

        javax.swing.GroupLayout lineGraphLayout = new javax.swing.GroupLayout(lineGraph);
        lineGraph.setLayout(lineGraphLayout);
        lineGraphLayout.setHorizontalGroup(
            lineGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineGraphLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        lineGraphLayout.setVerticalGroup(
            lineGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lineGraphLayout.createSequentialGroup()
                .addGap(0, 129, Short.MAX_VALUE)
                .addGroup(lineGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        fileMenu.setText("File");
        fileMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileMenuMouseClicked(evt);
            }
        });

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        menuQuit.setText("Quit");
        menuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitActionPerformed(evt);
            }
        });
        fileMenu.add(menuQuit);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tempLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempVal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uvButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temperatureButton)
                            .addComponent(humidityButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(windGustButton)
                            .addComponent(windSpeedButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rainfallButton)
                        .addGap(50, 50, 50)
                        .addComponent(windChillButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pressureButton)
                        .addGap(40, 40, 40)
                        .addComponent(heatButton)))
                .addGap(14, 14, 14))
            .addComponent(lineGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lineGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temperatureButton)
                    .addComponent(windSpeedButton)
                    .addComponent(tempLabel)
                    .addComponent(tempVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(humidityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(windGustButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rainfallButton)
                    .addComponent(windChillButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pressureButton)
                    .addComponent(heatButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uvButton)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Opens the File menu from the menu bar
     * @param evt the mouse click event
     */
    private void fileMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuMouseClicked

    /**
     * The Open action from the File menu
     * @param evt 
     */
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(FILES_AND_DIRECTORIES);
        fc.setMultiSelectionEnabled(true);
        FileFilter filter = new FileNameExtensionFilter("Weather files", "xml");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(openMenuItem);
        
        FilenameFilter xmlFilter = new FilenameFilter() {
			public boolean accept(File dir, String name) {
				String lowercaseName = name.toLowerCase();
				if (lowercaseName.endsWith(".xml")) {
					return true;
				} else {
					return false;
				}
			}
        };
        
        
        if ( returnVal == JFileChooser.APPROVE_OPTION )
        {
            XMLImport reader = new XMLImport();
            File[] files = fc.getSelectedFiles();
            List<File> filesForRead = new ArrayList<>();
            //This is where a real application would open the file.
            
            for (File file : files) {
                if (file.isDirectory()){
                    File[] moreFiles = (file.listFiles(xmlFilter));
                    for (File moreFile : moreFiles){
                        System.out.println( moreFile );
                        dataPoints = reader.readAll(filesForRead);
                    }
                }
                else {
                    filesForRead.add(file);
                }
                
                dataPoints = reader.readAll(filesForRead);
                // verify file is valid (somehow)
                // parse file using xml
                // append results to temp list
            }
            
            // add all new datapoints to dataPoints list at once
            // add all new datapoints to graph (s)
            
            System.out.println( "Opening: " + files[1].getName() + "." + "\n" );
        }
        else
        {
            System.out.println( "Open command cancelled by user." + "\n" );
        }
    }//GEN-LAST:event_openMenuItemActionPerformed

    
    private void menuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuQuitActionPerformed

    private void temperatureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureButtonActionPerformed
        // TODO add your handling code here:
        lineGraph.showTemperatureData();
    }//GEN-LAST:event_temperatureButtonActionPerformed

    private void pressureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressureButtonActionPerformed
        // TODO add your handling code here:
        lineGraph.showPressureData();
    }//GEN-LAST:event_pressureButtonActionPerformed

    private void uvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvButtonActionPerformed
        // TODO add your handling code here:
        lineGraph.showUVIndexData();
    }//GEN-LAST:event_uvButtonActionPerformed

    private void windSpeedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windSpeedButtonActionPerformed
        // TODO add your handling code here:
        windSpeedButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_windSpeedButtonActionPerformed

    private void windChillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windChillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_windChillButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeathermanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeathermanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeathermanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeathermanWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeathermanWindow("Weatherman App").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup dataOptions;
    private javax.swing.JMenu editMenu;
    private javax.swing.JSpinner endDate;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButton heatButton;
    private javax.swing.JRadioButton humidityButton;
    private com.hardcoders.csc468.weather.WeathermanLineGraph lineGraph;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuQuit;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JRadioButton pressureButton;
    private javax.swing.JRadioButton rainfallButton;
    private javax.swing.JSpinner startDate;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel tempVal;
    private javax.swing.JRadioButton temperatureButton;
    private javax.swing.JRadioButton uvButton;
    private javax.swing.JRadioButton windChillButton;
    private javax.swing.JRadioButton windGustButton;
    private javax.swing.JRadioButton windSpeedButton;
    // End of variables declaration//GEN-END:variables
}
